<a href="https://colab.research.google.com/github/cr21/Unsupervised-Machine-Learning-Clustering/blob/main/GaussianMixuerModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
cd drive/MyDrive/Dataset/

/content/drive/MyDrive/Dataset


In [ ]:
import numpy as np
from sklearn.datasets import make_spd_matrix
from scipy.stats import multivariate_normal

In [ ]:
gaussian2D = np.loadtxt('2gaussian.txt')
featureSize = gaussian2D.shape[1]
featureSize

2

In [ ]:

# initialize Mean
means = np.random.rand(2,2)
# mean = mean.tolist()


# initialize Covariance matrix
CovarianceMatrix = []
for j in range(len(means)):
  CovarianceMatrix.append(make_spd_matrix(2, j+ 42))
CovarianceMatrix



# intialize Weights of cluster
# prior distrution dirichlet 
weights = np.random.dirichlet(np.ones(2),size=1)
weights = weights.reshape((2,))

In [ ]:
gaussian2D.shape

(6000, 2)

In [ ]:
k = 2
STEP_SIZE = 10000

while STEP_SIZE > 0 :

  STEP_SIZE -= 1

  # E step
  MLE = []
  for num  in range(k):
    # get Probability of X given Mean and Covariance  for each cluter
    pdf  = multivariate_normal.pdf(gaussian2D, mean = means[num], cov= CovarianceMatrix[num])
    MLE.append(pdf)

  MLE = np.array(MLE)
  # testing it should be (2, 6000)
  # assert MLE.shape == (k, len(gaussian2D))

  PI_K = []
  # M Step
  
  for j in range(k) :
    # Normalize the probablity and calculate the PI_K
    PI_K.append( MLE[j] * weights[j]/  (np.sum([ weights[i] * MLE[i] for i in  range(k)], axis=0) + 10e-5))
    # np.sum(PI_K.reshape(len(gaussian2D),1) * X, axis=0) / (np.sum(b[j]+eps))
    means[j] = np.sum(PI_K[j].reshape(len(gaussian2D),1) * gaussian2D, axis= 0 ) / (np.sum(PI_K[j] + 10e-5))
    numerator = np.dot ( (PI_K[j].reshape(len(gaussian2D),1) *  (gaussian2D - means[j])).T , (gaussian2D - means[j]) )
    denom =   np.sum(PI_K[j]  + 10e-5)
    CovarianceMatrix[j] = numerator/denom
    weights[j] = np.mean(PI_K[j])
  print(STEP_SIZE)
   



In [115]:
for j in range(k):
  print("______________")
  print(" Cluster number : ", j)
  print("means ")
  print(means3d[j])
  print("Covariance matrix ")
  print(CovarianceMatrix3d[j])
  print("weights :")
  print(weights3d[j])
  print("____________________")

______________
 Cluster number :  0
means 
[7.01015634 4.01128267]
Covariance matrix 
[[0.98363366 0.49709061]
 [0.49709061 0.97900783]]
weights :
0.29661434318112995
____________________
______________
 Cluster number :  1
means 
[5.00415077 6.99207789]
Covariance matrix 
[[0.97325097 0.18359831]
 [0.18359831 0.95314011]]
weights :
0.4944623196676408
____________________


In [116]:
gaussian3D = np.loadtxt('3gaussian.txt')
featureSize = gaussian3D.shape[1]
featureSize

2

In [117]:

# initialize Mean
means3d = np.random.rand(3,2)
# mean = mean.tolist()


# initialize Covariance matrix
CovarianceMatrix3d = []
for j in range(len(means3d)):
  CovarianceMatrix3d.append(make_spd_matrix(2, j+ 42))
CovarianceMatrix3d



# intialize Weights of cluster
# prior distrution dirichlet 
weights3d = np.random.dirichlet(np.ones(3),size=1)
weights3d = weights3d.reshape((3,))

In [118]:
CovarianceMatrix3d

[array([[2.09417602, 0.34617642],
        [0.34617642, 0.21783715]]), array([[2.28664883, 0.76798353],
        [0.76798353, 0.89962772]]), array([[ 1.91873603, -0.909318  ],
        [-0.909318  ,  1.04981319]])]

In [ ]:
k = 3
STEP_SIZE = 1000

while STEP_SIZE > 0 :

  STEP_SIZE -= 1

  # E step
  MLE3d = []
  for num  in range(k):
    # get Probability of X given Mean and Covariance  for each cluter
    pdf  = multivariate_normal.pdf(gaussian3D, mean = means3d[num], cov= CovarianceMatrix3d[num])
    MLE3d.append(pdf)

  MLE3d = np.array(MLE3d)
  # testing it should be (2, 6000)
  # assert MLE.shape == (k, len(gaussian2D))

  PI_K = []
  # M Step
  
  for j in range(k) :
    # Normalize the probablity and calculate the PI_K
    PI_K.append( MLE3d[j] * weights3d[j]/  (np.sum([ weights3d[i] * MLE3d[i] for i in  range(k)], axis=0) + 10e-5))
    # np.sum(PI_K.reshape(len(gaussian2D),1) * X, axis=0) / (np.sum(b[j]+eps))
    means3d[j] = np.sum(PI_K[j].reshape(len(gaussian3D),1) * gaussian3D, axis= 0 ) / (np.sum(PI_K[j] + 10e-5))
    numerator = np.dot ( (PI_K[j].reshape(len(gaussian3D),1) *  (gaussian3D - means3d[j])).T , (gaussian3D - means3d[j]) )
    denom =   np.sum(PI_K[j]  + 10e-5)
    CovarianceMatrix3d[j] = numerator/denom
    weights3d[j] = np.mean(PI_K[j])
  print(STEP_SIZE)
   



In [120]:
for j in range(k):
  print("______________")
  print(" Cluster number : ", j)
  print("means ")
  print(means3d[j])
  print("Covariance matrix ")
  print(CovarianceMatrix3d[j])
  print("weights :")
  print(weights3d[j])
  print("____________________")

______________
 Cluster number :  0
means 
[7.01015634 4.01128267]
Covariance matrix 
[[0.98363366 0.49709061]
 [0.49709061 0.97900783]]
weights :
0.29661434318113006
____________________
______________
 Cluster number :  1
means 
[5.00415077 6.99207789]
Covariance matrix 
[[0.97325097 0.18359831]
 [0.18359831 0.95314011]]
weights :
0.4944623196676408
____________________
______________
 Cluster number :  2
means 
[3.03687463 3.03650199]
Covariance matrix 
[[0.97633032 0.03272165]
 [0.03272165 3.16993496]]
weights :
0.19869003095420568
____________________
